# Generated by Django 4.0.2 on 2023-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0002_biochemicalbloodanalysis_bodymassindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronaryangiography',
            name='field',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4+')], default='', max_length=1, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='ecg',
            name='field',
            field=models.CharField(choices=[('ST_1', 'Подъём сегманта ST'), ('ST_2', 'Депрессия сегманта ST'), ('T', 'Инверсия зубца T')], default='', max_length=4, verbose_name='Поле'),
        ),
    ]
