# Generated by Django 4.0.2 on 2023-06-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0003_alter_coronaryangiography_field_alter_ecg_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echocardiography',
            old_name='end_systolic_size',
            new_name='kcr',
        ),
        migrations.AddField(
            model_name='echocardiography',
            name='kdr',
            field=models.FloatField(default=0, verbose_name='КДР (см)'),
        ),
    ]
