# Generated by Django 4.0.2 on 2023-06-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0004_rename_end_systolic_size_echocardiography_kcr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='geneticresearch',
            name='IL_4_TC',
            field=models.CharField(choices=[('1', 'C/C'), ('2', 'C/T'), ('3', 'T/T')], default='', max_length=3, verbose_name='IL-1β 511 T/C (rs2243250)'),
        ),
        migrations.AddField(
            model_name='geneticresearch',
            name='TNF_a_GA',
            field=models.CharField(choices=[('1', 'G/G'), ('2', 'G/A'), ('3', 'A/A')], default='', max_length=3, verbose_name='TNF-α G/A 308 (rs1800629)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.FloatField(default=0, verbose_name='ЧСС'),
        ),
        migrations.AlterField(
            model_name='geneticresearch',
            name='IL_10_819_CT',
            field=models.CharField(choices=[('1', 'C/C'), ('2', 'C/T'), ('3', 'T/T')], default='', max_length=3, verbose_name='IL-10 819 C/T (rs1800871)'),
        ),
        migrations.AlterField(
            model_name='geneticresearch',
            name='IL_1b_511_TC',
            field=models.CharField(choices=[('1', 'C/C'), ('2', 'C/T'), ('3', 'T/T')], default='', max_length=3, verbose_name='IL-1β 511 T/C (rs16944)'),
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='Вопрос')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtools.survey', verbose_name='Опросник')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtools.surveyquestion', verbose_name='Вопрос')),
            ],
        ),
    ]
