# Generated by Django 4.0.2 on 2023-06-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0005_survey_geneticresearch_il_4_tc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echocardiography',
            name='patient',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medtools.patient', verbose_name='Пациент'),
        ),
    ]
