# Generated by Django 4.0.2 on 2023-06-06 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medtools', '0006_alter_echocardiography_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='ACAT',
            field=models.FloatField(default=0, verbose_name='АСАТ(U/L)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='ALAT',
            field=models.FloatField(default=0, verbose_name='АЛАТ (U/L)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='bilirubin_common',
            field=models.FloatField(default=0, verbose_name='Билурибин общий (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='bilirubin_direct',
            field=models.FloatField(default=0, verbose_name='Билурибин прямой (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='bilirubin_indirect',
            field=models.FloatField(default=0, verbose_name='Билурибин непрямой (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='creotenin',
            field=models.FloatField(default=0, verbose_name='Креотенин (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='glucose',
            field=models.FloatField(default=0, verbose_name='Глюкоза (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='urea',
            field=models.FloatField(default=0, verbose_name='Мочевина Креотенин (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='uric_acid',
            field=models.FloatField(default=0, verbose_name='Мочевая кислота(мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='bodymassindex',
            name='height',
            field=models.FloatField(default=0, verbose_name='Рост (cм)'),
        ),
        migrations.AlterField(
            model_name='bodymassindex',
            name='mass',
            field=models.FloatField(default=0, verbose_name='Mass (кг)'),
        ),
        migrations.AlterField(
            model_name='coronaryangiography',
            name='field',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4+')], default='', max_length=1, verbose_name='Количество поражений КА'),
        ),
    ]
