# Generated by Django 4.0.2 on 2023-06-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0007_surveyanswer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question',
        ),
        migrations.CreateModel(
            name='SurveyQuestionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(default='', max_length=100, verbose_name='Выбор')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medtools.surveyquestion', verbose_name='Вопрос')),
            ],
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medtools.surveyquestionchoices', verbose_name='Выбор'),
        ),
    ]
