# Generated by Django 4.0.2 on 2023-06-06 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0008_remove_surveyanswer_question_surveyquestionchoices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medtools.patient', verbose_name='Пациент'),
        ),
    ]
