# Generated by Django 4.0.2 on 2023-06-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0010_alter_surveyanswer_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medtools.survey', verbose_name='Опросник'),
        ),
    ]
