# Generated by Django 4.0.2 on 2023-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0011_surveyanswer_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey',
        ),
        migrations.AddField(
            model_name='surveyquestionchoices',
            name='mark',
            field=models.SmallIntegerField(default=0, verbose_name='Балл'),
        ),
    ]
