# Generated by Django 4.0.2 on 2023-06-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0012_remove_surveyanswer_survey_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyanswer',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='has_multiple_choice',
            field=models.BooleanField(default=False, verbose_name='Множественный выбор'),
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255, verbose_name='Текст')),
                ('mark_from', models.IntegerField(default=0, verbose_name='Мин балл для вывода')),
                ('mark_to', models.IntegerField(default=0, verbose_name='Макс балл для вывода')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtools.survey', verbose_name='Опросник')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyMultipleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ManyToManyField(related_name='choices', to='medtools.SurveyQuestionChoices', verbose_name='Выбор')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medtools.patient', verbose_name='Пациент')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
