# Generated by Django 4.0.2 on 2023-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0013_alter_surveyanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymultipleanswer',
            name='choice',
            field=models.ManyToManyField(blank=True, related_name='choices', to='medtools.SurveyQuestionChoices', verbose_name='Выбор'),
        ),
    ]
