# Generated by Django 4.0.2 on 2023-06-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0014_alter_surveymultipleanswer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
