# Generated by Django 4.0.2 on 2023-06-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0015_remove_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipidogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HS', models.FloatField(default=0, verbose_name='Общий ХС ммоль/г')),
                ('HS_LPNP', models.FloatField(default=0, verbose_name='ХС ЛПНП. ммоль/г')),
                ('HS_LPVP', models.FloatField(default=0, verbose_name='ХС ЛПВП. ммоль/г')),
                ('TG', models.FloatField(default=0, verbose_name='ТГ. ммоль/г')),
                ('KAT', models.FloatField(default=0, verbose_name='КАТ')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medtools.patient', verbose_name='Пациент')),
            ],
        ),
        migrations.RemoveField(
            model_name='biochemicalbloodanalysis',
            name='creotenin',
        ),
        migrations.AddField(
            model_name='biochemicalbloodanalysis',
            name='creatinin',
            field=models.FloatField(default=0, verbose_name='Rреатинин (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='bilirubin_common',
            field=models.FloatField(default=0, verbose_name='Билирубин общий (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='bilirubin_direct',
            field=models.FloatField(default=0, verbose_name='Билирубин прямой (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='bilirubin_indirect',
            field=models.FloatField(default=0, verbose_name='Билирубин непрямой (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='urea',
            field=models.FloatField(default=0, verbose_name='Мочевина (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='bodymassindex',
            name='mass',
            field=models.FloatField(default=0, verbose_name='Масса (кг)'),
        ),
        migrations.AlterField(
            model_name='geneticresearch',
            name='IL_4_TC',
            field=models.CharField(choices=[('1', 'C/C'), ('2', 'C/T'), ('3', 'T/T')], default='', max_length=3, verbose_name='IL-4 С/Т (rs2243250)'),
        ),
        migrations.DeleteModel(
            name='pilidogram',
        ),
    ]
