# Generated by Django 4.0.2 on 2023-06-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0016_lipidogram_remove_biochemicalbloodanalysis_creotenin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipidogram',
            name='KAT',
        ),
        migrations.AddField(
            model_name='lipidogram',
            name='KA',
            field=models.FloatField(default=0, verbose_name='КА'),
        ),
    ]
