# Generated by Django 4.0.2 on 2023-06-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0017_remove_lipidogram_kat_lipidogram_ka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациента', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Опросник', 'verbose_name_plural': 'Опросники'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'verbose_name': 'Вопрос опросника', 'verbose_name_plural': 'Вопросы для опросников'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestionchoices',
            options={'verbose_name': 'Выбор для вопроса', 'verbose_name_plural': 'Выборы для вопросов'},
        ),
        migrations.AlterModelOptions(
            name='surveyresult',
            options={'verbose_name': 'Результат для опросника', 'verbose_name_plural': 'Результаты для опросников'},
        ),
        migrations.AlterField(
            model_name='biochemicalbloodanalysis',
            name='creatinin',
            field=models.FloatField(default=0, verbose_name='Креатинин (мкмоль/л)'),
        ),
        migrations.AlterField(
            model_name='echocardiography',
            name='eslj',
            field=models.FloatField(default=0, verbose_name='ЗСЛЖ (см)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(choices=[('>60', 'Старше 60'), ('<60', 'Младше 60')], default='', max_length=3, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_position',
            field=models.CharField(choices=[('S', 'Удовлетворительно'), ('D', 'Неудовлетворительно')], default='', max_length=1, verbose_name='Социальный статус'),
        ),
    ]
