# Generated by Django 4.0.2 on 2023-06-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0018_alter_patient_options_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_en',
            field=models.TextField(default='', null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_ru',
            field=models.TextField(default='', null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_uz',
            field=models.TextField(default='', null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='surveyquestionchoices',
            name='choice_text_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Выбор'),
        ),
        migrations.AddField(
            model_name='surveyquestionchoices',
            name='choice_text_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Выбор'),
        ),
        migrations.AddField(
            model_name='surveyquestionchoices',
            name='choice_text_uz',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Выбор'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='text_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='text_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='text_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
