# Generated by Django 4.0.2 on 2023-06-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0018_alter_surveymultipleanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveymultipleanswer',
            name='question',
        ),
    ]
