# Generated by Django 4.0.2 on 2023-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtools', '0019_survey_name_en_survey_name_ru_survey_name_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chronic_heart_failure',
            field=models.BooleanField(default=False, verbose_name='Хроническая сердечная недостаточность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='congestive_heart_failure',
            field=models.BooleanField(default=False, verbose_name='Острая сердечная недостаточность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='heart_rate',
            field=models.FloatField(default=0, verbose_name='Частота сердечных сокращений'),
        ),
    ]
