# Generated by Django 4.0.2 on 2023-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя, Фамилия')),
                ('full_name_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя, Фамилия')),
                ('full_name_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя, Фамилия')),
                ('full_name_uz', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя, Фамилия')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug статьи')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
