# Generated by Django 4.0.2 on 2023-02-21 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_user', to=settings.AUTH_USER_MODEL, verbose_name='Зарегестрированный пользователь'),
        ),
        migrations.CreateModel(
            name='ReviewersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя, Фамилия')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug статьи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='Зарегестрированный пользователь')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
