# Generated by Django 4.0.2 on 2023-02-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_reviewersprofile_full_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewersprofile',
            options={'verbose_name': 'Рецензента', 'verbose_name_plural': 'Рецензенты'},
        ),
    ]
