# Generated by Django 4.0.2 on 2023-02-10 12:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название раздела')),
                ('title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Название раздела')),
                ('title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы статьи',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Ф.И.О.')),
                ('name_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Ф.И.О.')),
                ('name_en', models.CharField(default='', max_length=255, null=True, verbose_name='Ф.И.О.')),
                ('slug', models.SlugField(max_length=200, null=True, verbose_name='Slug тома')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ключевое слово')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Ключевое слово')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Ключевое слово')),
                ('related_articles_number', models.IntegerField(default=0, verbose_name='Количество связанных статей')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UniqueViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Уникального пользователя',
                'verbose_name_plural': 'Уникальные пользователи',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название тома')),
                ('title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Название тома')),
                ('title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Название тома')),
                ('doi', models.CharField(default='', max_length=255, verbose_name='DOI ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('qr', models.ImageField(upload_to='images/volumes/QR/', verbose_name='QR-код')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug тома')),
                ('status_str', models.CharField(blank=True, max_length=100, verbose_name='Строка статуса')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.state', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Том',
                'verbose_name_plural': 'Тома',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='Заголовок статьи')),
                ('title_ru', models.CharField(default='', max_length=255, null=True, unique=True, verbose_name='Заголовок статьи')),
                ('title_en', models.CharField(default='', max_length=255, null=True, unique=True, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug статьи')),
                ('annotation', ckeditor.fields.RichTextField(default='', verbose_name='Аннотация')),
                ('annotation_ru', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Аннотация')),
                ('annotation_en', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Аннотация')),
                ('for_quoting', models.TextField(blank=True, default='', null=True, verbose_name='Для цитирования')),
                ('for_quoting_ru', models.TextField(blank=True, default='', null=True, verbose_name='Для цитирования')),
                ('for_quoting_en', models.TextField(blank=True, default='', null=True, verbose_name='Для цитирования')),
                ('doi', models.CharField(default='', max_length=255, null=True, verbose_name='DOI ссылка')),
                ('qr', models.ImageField(upload_to='images/articles/QR/', verbose_name='QR-код')),
                ('file', models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)')),
                ('file_ru', models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)')),
                ('file_en', models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)')),
                ('authors_text', models.CharField(default='', max_length=255, verbose_name='Авторы (Текст)')),
                ('authors_text_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Авторы (Текст)')),
                ('authors_text_en', models.CharField(default='', max_length=255, null=True, verbose_name='Авторы (Текст)')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показывать на сайте')),
                ('authors', models.ManyToManyField(blank=True, related_name='authors', to='blogs.Authors', verbose_name='Связанные Авторы')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.articlesection', verbose_name='Раздел')),
                ('linked_volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.volume', verbose_name='Связанный том')),
                ('tags', models.ManyToManyField(related_name='tags', to='blogs.Tags', verbose_name='Ключевые слова')),
                ('viewers', models.ManyToManyField(related_name='viewers', to='blogs.UniqueViewers', verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
                'ordering': ['published_date', 'title'],
            },
        ),
    ]
