# Generated by Django 4.0.2 on 2023-02-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='qr',
        ),
        migrations.AlterField(
            model_name='volume',
            name='qr',
            field=models.ImageField(blank=True, upload_to='images/volumes/QR/', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название тома'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название тома'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='title_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название тома'),
        ),
    ]
