# Generated by Django 4.0.2 on 2023-02-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='profiles.AuthorsProfile', verbose_name='Связанные Авторы'),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.articlesection', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='article',
            name='linked_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.volume', verbose_name='Связанный том'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blogs.Tags', verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to='blogs.UniqueViewers', verbose_name='Просмотры'),
        ),
    ]
