# Generated by Django 4.0.2 on 2023-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='qr',
        ),
        migrations.AlterField(
            model_name='volume',
            name='qr',
            field=models.ImageField(blank=True, upload_to='images/volumes/QR/', verbose_name='QR-код'),
        ),
    ]
