# Generated by Django 4.0.2 on 2023-02-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_article_qr_alter_volume_qr_alter_volume_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
    ]
