# Generated by Django 4.0.2 on 2023-02-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_article_title_alter_article_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug статьи'),
        ),
        migrations.AddField(
            model_name='volume',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug тома'),
        ),
        migrations.AddField(
            model_name='volume',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug тома'),
        ),
    ]
