# Generated by Django 4.0.2 on 2023-02-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_volume_status_str_alter_volume_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='status',
            field=models.CharField(blank=True, choices=[('активный', 'активный'), ('неактивный', 'неактивный'), ('архивный', 'архивный'), ('следующий', 'следующий')], max_length=100, verbose_name='Строка статуса'),
        ),
    ]
