# Generated by Django 4.0.2 on 2023-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_article_title_alter_article_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
