# Generated by Django 4.0.2 on 2023-02-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_volume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags_text',
            field=models.TextField(default='', verbose_name='Ключевые слова (от автора)'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='status',
            field=models.CharField(blank=True, choices=[('Активный', 'Активный'), ('Неактивный', 'Неактивный'), ('Архивный', 'Архивный'), ('Следующий', 'Следующий')], max_length=100, verbose_name='Строка статуса'),
        ),
    ]
