# Generated by Django 4.0.2 on 2023-02-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_article_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Авторы сайта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
    ]
