# Generated by Django 4.0.2 on 2023-02-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_article_slug_en_article_slug_ru_volume_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='slug_ru',
        ),
    ]
