# Generated by Django 4.0.2 on 2023-02-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_article_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('рецензируется', 'Рецензируется'), ('отклонено', 'Отклонено'), ('принят', 'Принят'), ('опубликован', 'Опубликован')], default='черновик', max_length=100, verbose_name='Статус'),
        ),
    ]
