# Generated by Django 4.0.2 on 2023-02-18 08:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_article_is_active_article_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='annotation_uz',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='article',
            name='authors_text_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Авторы (Текст)'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_uz',
            field=models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)'),
        ),
        migrations.AddField(
            model_name='article',
            name='for_quoting_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Для цитирования'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='title_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='tags',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Ключевое слово'),
        ),
        migrations.AddField(
            model_name='volume',
            name='file_uz',
            field=models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
        migrations.AddField(
            model_name='volume',
            name='title_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название тома'),
        ),
    ]
