# Generated by Django 4.0.2 on 2023-02-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время комментирования'),
        ),
    ]
