# Generated by Django 4.0.2 on 2023-02-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_reviewersprofile_options'),
        ('blogs', '0007_comment_is_recommended_alter_comment_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='profiles.reviewersprofile', verbose_name='Рецензент'),
        ),
    ]
