# Generated by Django 4.0.2 on 2023-02-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
