# Generated by Django 4.0.2 on 2023-03-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors_text_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors_text_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors_text_uz',
        ),
    ]
