# Generated by Django 4.0.2 on 2023-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_remove_article_authors_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blogs.Tags', verbose_name='Ключевые слова'),
        ),
    ]
