# Generated by Django 4.0.2 on 2023-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orcid',
            field=models.CharField(default='', max_length=255, verbose_name='ORCID'),
        ),
    ]
