# Generated by Django 4.0.2 on 2023-02-18 08:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialmember',
            name='about_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Об авторе'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='full_name_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AddField(
            model_name='editorialmember',
            name='location_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название страницы'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
