# Generated by Django 4.0.2 on 2023-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя, Фамилия'),
        ),
    ]
