# Generated by Django 4.0.2 on 2023-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_profile', '0003_authorsprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsprofile',
            name='full_name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя, Фамилия'),
        ),
        migrations.AddField(
            model_name='authorsprofile',
            name='full_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя, Фамилия'),
        ),
    ]
