# Generated by Django 4.0.2 on 2023-02-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_profile', '0004_authorsprofile_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsprofile',
            name='full_name_uz',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя, Фамилия'),
        ),
    ]
